# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----

pipelines:
  branches:
    master:
      - step:
          image: node:8.10.0
          caches:
            - node
          script: #Modify the commands below to build your repository.
            - npm install
            - npm run build:demo
            - echo 'successfully build!'
          artifacts: #Defining the artifacts to be passed to each future step.
            - dist/**
      - step:
          name: S3 staging-Compressing files
          script:
            - ./compress.sh   #Calling compress.sh to uglify files and compressing build 
      - step:
          name: S3 staging-Deploying FlowUI
          deployment: staging
          trigger: manual
          image: atlassian/pipelines-awscli
          script:
            - echo 'Deleting old build from s3'
            - aws s3 rm s3://$AWS_BUCKET_TARGET --recursive
            - echo 'Deleted old build from s3'
            - echo 'Uploading new build on s3'
            - aws s3 cp ./dist/ s3://$AWS_BUCKET_TARGET/ --recursive
            - echo 'build upload successful!'
    domain2.0:
      - step:
          image: node:8.10.0
          caches:
            - node
          script: #Modify the commands below to build your repository.
            - npm install
            - npm run build:demo
            - echo 'successfully build!'
          artifacts: #Defining the artifacts to be passed to each future step.
            - dist/**
      - step:
          name: S3 staging-Compressing files
          script:
            - ./compress.sh   #Calling compress.sh to uglify files and compressing build 
      - step:
          name: S3 staging-Deploying FlowUI
          deployment: staging
          image: atlassian/pipelines-awscli
          script:
            - echo 'Deleting old build from s3'
            - aws s3 rm s3://$AWS_BUCKET_TARGET --recursive
            - echo 'Deleted old build from s3'
            - echo 'Uploading new build on s3'
            - aws s3 cp ./dist/ s3://$AWS_BUCKET_TARGET/ --recursive
            - echo 'build upload successful!'

