# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----

pipelines:
  custom:
    master:
    - step:
          name: FlowUI-Demo Build and Release
          image: node:8.10.0
          caches:
            - node
          script: #Modify the commands below to build your repository.
            - npm install
            - npm run build:demo
            - echo 'successfully build!'
          artifacts: #Defining the artifacts to be passed to each future step.
            - dist/**
    - step:
          name: FlowUI-Demo-Compressing files
          script:
            - ./compress.sh   #Calling compress.sh to uglify files and compressing build 
    - step:
          name: FlowUI Demo Deployment
          deployment: staging
          image: atlassian/pipelines-awscli
          script:
            - echo 'Deleting old build from s3'
            - aws s3 rm s3://$AWS_BUCKET_TARGET --recursive
            - echo 'Deleted old build from s3'
            - echo 'Uploading new build on s3'
            - aws s3 cp ./dist/ s3://$AWS_BUCKET_TARGET/ --recursive
            - echo 'build upload successful!'
  tags:                        
    RELEASE*:                 
    - step:                   
        name: Tag based Prod Build and release
        image: 'node:8.10.0'
        caches:
          - node
        script: #Modify the commands below to build your repository.
            - npm install
            - npm run build:prod
            - echo 'successfully build!'
        artifacts: #Defining the artifacts to be passed to each future step.
            - dist/**
    - step:
          name: S3 Prod-Compressing files
          script:
            - ./compress.sh   #Calling compress.sh to uglify files and compressing build 
    - step:
          name: FlowUI Prod Deployment
          deployment: production
          trigger: manual
          image: atlassian/pipelines-awscli
          script:
            - echo 'Deleting old build from s3'
            - aws s3 rm s3://$AWS_BUCKET_TARGET --recursive
            - echo 'Deleted old build from s3'
            - echo 'Uploading new build on s3'
            - aws s3 cp ./dist/ s3://$AWS_BUCKET_TARGET/ --recursive
            - echo 'build upload successful!'
  branches:
    compusoft:
      - step:                   
          name: Branch based Prod Build and release
          image: 'node:8.10.0'
          caches:
            - node
          script: #Modify the commands below to build your repository.
            - npm install
            - npm run build:prod
            - echo 'successfully build!'
          artifacts: #Defining the artifacts to be passed to each future step.
            - dist/**
      - step:
          name: S3 Prod-Compressing files
          deployment: staging
          image: atlassian/pipelines-awscli
          script:
            - ./compress.sh   #Calling compress.sh to uglify files and compressing build  
            - ./create_artifact.sh
            - aws s3 cp flow-ui.zip s3://automatapi-build-artifacts/compusoft/flow-ui/release/
      

